import { HealthState } from "@/types/health";

const today = new Date();
const daysAgo = (n: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() - n);
  return d.toISOString();
};

export const SEED_STATE: HealthState = {
  patientName: "Arjun Sharma",
  abhaLinked: true,
  healthScore: 72,
  continuityScore: 84,
  documents: [
    {
      id: "doc-1",
      title: "Dr Lal PathLabs — Diabetes Panel",
      source: "upload",
      status: "completed",
      uploadedAt: daysAgo(7),
      language: "english",
      confidence: 0.97,
      extractedDiagnoses: ["Type 2 Diabetes"],
    },
    {
      id: "doc-2",
      title: "Apollo Clinic — Consultation Note",
      source: "whatsapp",
      status: "completed",
      uploadedAt: daysAgo(21),
      language: "english",
      confidence: 0.92,
    },
    {
      id: "doc-3",
      title: "Thyrocare — Lipid Profile",
      source: "upload",
      status: "completed",
      uploadedAt: daysAgo(45),
      language: "english",
      confidence: 0.95,
    },
  ],
  labs: [
    {
      id: "lab-1",
      name: "HbA1c",
      value: 7.8,
      unit: "%",
      status: "HIGH",
      date: daysAgo(7),
      referenceLow: 4.0,
      referenceHigh: 5.7,
      documentId: "doc-1",
    },
    {
      id: "lab-2",
      name: "Fasting Glucose",
      value: 142,
      unit: "mg/dL",
      status: "HIGH",
      date: daysAgo(7),
      referenceLow: 70,
      referenceHigh: 99,
      documentId: "doc-1",
    },
    {
      id: "lab-3",
      name: "Total Cholesterol",
      value: 218,
      unit: "mg/dL",
      status: "HIGH",
      date: daysAgo(45),
      referenceLow: 0,
      referenceHigh: 200,
      documentId: "doc-3",
    },
    {
      id: "lab-4",
      name: "LDL",
      value: 132,
      unit: "mg/dL",
      status: "HIGH",
      date: daysAgo(45),
      referenceLow: 0,
      referenceHigh: 100,
      documentId: "doc-3",
    },
    {
      id: "lab-5",
      name: "HDL",
      value: 48,
      unit: "mg/dL",
      status: "NORMAL",
      date: daysAgo(45),
      referenceLow: 40,
      referenceHigh: 60,
      documentId: "doc-3",
    },
    {
      id: "lab-6",
      name: "Creatinine",
      value: 0.9,
      unit: "mg/dL",
      status: "NORMAL",
      date: daysAgo(7),
      referenceLow: 0.7,
      referenceHigh: 1.3,
      documentId: "doc-1",
    },
    {
      id: "lab-7",
      name: "HbA1c",
      value: 7.2,
      unit: "%",
      status: "HIGH",
      date: daysAgo(120),
      referenceLow: 4.0,
      referenceHigh: 5.7,
    },
    {
      id: "lab-8",
      name: "HbA1c",
      value: 6.8,
      unit: "%",
      status: "HIGH",
      date: daysAgo(240),
      referenceLow: 4.0,
      referenceHigh: 5.7,
    },
  ],
  medications: [
    {
      id: "med-1",
      name: "Metformin",
      dose: "500 mg",
      frequency: "Twice daily",
      prescribedBy: "Dr Sharma",
      startDate: daysAgo(180),
      active: true,
    },
    {
      id: "med-2",
      name: "Atorvastatin",
      dose: "10 mg",
      frequency: "Once at night",
      prescribedBy: "Dr Sharma",
      startDate: daysAgo(45),
      active: true,
    },
    {
      id: "med-3",
      name: "Telmisartan",
      dose: "40 mg",
      frequency: "Once in morning",
      prescribedBy: "Dr Iyer",
      startDate: daysAgo(90),
      active: true,
    },
  ],
  diagnoses: [
    {
      id: "dx-1",
      name: "Type 2 Diabetes Mellitus",
      date: daysAgo(540),
      doctor: "Dr Sharma",
    },
    {
      id: "dx-2",
      name: "Essential Hypertension",
      date: daysAgo(420),
      doctor: "Dr Iyer",
    },
    {
      id: "dx-3",
      name: "Mixed Dyslipidemia",
      date: daysAgo(45),
      doctor: "Dr Sharma",
    },
  ],
  visits: [
    {
      id: "visit-1",
      date: daysAgo(7),
      doctor: "Dr Sharma",
      hospital: "Apollo Clinic, Bandra",
      notes: "Diabetes review. HbA1c trending up. Discussed adherence and diet.",
      documentId: "doc-1",
    },
    {
      id: "visit-2",
      date: daysAgo(45),
      doctor: "Dr Sharma",
      hospital: "Apollo Clinic, Bandra",
      notes: "Lipid profile review. Started atorvastatin 10mg.",
      documentId: "doc-3",
    },
    {
      id: "visit-3",
      date: daysAgo(90),
      doctor: "Dr Iyer",
      hospital: "Hinduja Hospital",
      notes: "BP review. Increased telmisartan dose.",
    },
  ],
  alerts: [
    {
      id: "alert-1",
      title: "HbA1c worsening trend",
      description:
        "Your HbA1c rose from 6.8 to 7.8 over 8 months. Consider meeting Dr Sharma within 2 weeks.",
      severity: "warning",
      createdAt: daysAgo(7),
      acknowledged: false,
    },
    {
      id: "alert-2",
      title: "LDL above target",
      description:
        "LDL is 132 mg/dL — above your goal of 100 mg/dL. Atorvastatin started, recheck in 3 months.",
      severity: "warning",
      createdAt: daysAgo(45),
      acknowledged: false,
    },
    {
      id: "alert-3",
      title: "Medication refill due",
      description: "Metformin supply runs out in 5 days. Refill from your usual pharmacy.",
      severity: "info",
      createdAt: daysAgo(2),
      acknowledged: false,
    },
  ],
  tasks: [
    {
      id: "task-1",
      title: "Repeat HbA1c test",
      description: "Recommended in 3 months from last test.",
      dueDate: daysAgo(-83),
      priority: "high",
      status: "pending",
    },
    {
      id: "task-2",
      title: "BP check at home",
      description: "Log morning BP for the next 7 days.",
      dueDate: daysAgo(-1),
      priority: "moderate",
      status: "pending",
    },
    {
      id: "task-3",
      title: "Refill Metformin",
      dueDate: daysAgo(-5),
      priority: "high",
      status: "pending",
    },
    {
      id: "task-4",
      title: "Walk 30 min × 5 days",
      dueDate: daysAgo(-7),
      priority: "low",
      status: "pending",
    },
  ],
  family: [
    { id: "fam-1", name: "Priya Sharma", relation: "Spouse", age: 49, initials: "PS" },
    { id: "fam-2", name: "Maa", relation: "Mother", age: 78, initials: "M" },
    { id: "fam-3", name: "Aarav", relation: "Son", age: 18, initials: "A" },
  ],
  risks: [
    {
      category: "Diabetes",
      score: 68,
      trend: "worsening",
      factors: ["HbA1c 7.8%", "Fasting 142 mg/dL", "BMI 27.4"],
    },
    {
      category: "Cardiovascular",
      score: 54,
      trend: "stable",
      factors: ["LDL 132", "BP controlled", "Family history"],
    },
    {
      category: "Kidney",
      score: 18,
      trend: "stable",
      factors: ["Creatinine normal", "eGFR > 90"],
    },
  ],
  messages: [
    {
      id: "msg-welcome",
      role: "assistant",
      text: "Namaste Arjun. I'm Swastha AI — your private health memory. Ask me anything about your reports, meds, trends, or risks. Try: 'What's my latest HbA1c?' or 'Summarise my last 3 months.'",
      createdAt: new Date().toISOString(),
    },
  ],
};
